"""
title: EmailSender Markdown Multipart Pipeline
author: Christopher Vaz, modified for Markdown/HTML multipart email
date: 2026-06-25
version: 1.1
license: MIT
description: A pipeline for sending AI-generated email reports using SMTP. Accepts Markdown, converts it to HTML, and sends multipart/alternative email with text/plain and text/html parts.
"""

import smtplib
import json
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import List
from pydantic import BaseModel, Field

try:
    import markdown
except (
    ImportError
):  # keeps the tool from crashing at import time if dependency is missing
    markdown = None


class Tools:
    def get_user_name_and_email_and_id(self, __user__: dict = {}) -> str:
        """
        Get the user name, email, and ID from the user object.
        """
        print(__user__)
        result = ""

        if "name" in __user__:
            result += f"User: {__user__['name']}"
        if "id" in __user__:
            result += f" (ID: {__user__['id']})"
        if "email" in __user__:
            result += f" (Email: {__user__['email']})"

        if result == "":
            result = "User: Unknown"

        return result

    def _markdown_to_html(self, markdown_body: str) -> str:
        """
        Convert Markdown to full HTML email body.
        Requires the third-party Python package: Markdown
        Install with: pip install Markdown
        """
        if markdown is None:
            raise RuntimeError(
                "Missing dependency: Markdown. Install it with: pip install Markdown"
            )

        body_html = markdown.markdown(
            markdown_body,
            extensions=["extra", "tables", "fenced_code", "sane_lists", "nl2br"],
            output_format="html5",
        )

        # Basic email-safe wrapper. Keep CSS inline/simple because Gmail strips some styles.
        return f"""<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body style="font-family: Arial, Helvetica, sans-serif; line-height: 1.5; color: #222; margin: 0; padding: 24px;">
    <div style="max-width: 760px; margin: 0 auto;">
      {body_html}
      <hr style="border: none; border-top: 1px solid #ddd; margin: 24px 0;">
      <p style="font-size: 12px; color: #666;">
        This email was generated by an AI assistant and sent with user consent.
      </p>
    </div>
  </body>
</html>"""

    def send_email(self, subject: str, body: str, recipients: List[str]) -> str:
        """
        Send a Markdown-authored email as multipart/alternative.

        The LLM should provide the body in Markdown, not raw HTML.
        This tool converts Markdown to HTML, then sends both:
        - text/plain fallback containing the original Markdown
        - text/html rendered version for Gmail and modern email clients

        DO NOT SEND WITHOUT USER'S CONSENT. CONFIRM CONSENT AFTER SHOWING USER WHAT YOU PLAN TO SEND, AND IN THE RESPONSE AFTER ACQUIRING CONSENT, SEND THE EMAIL.

        :param subject: The subject of the email.
        :param body: The Markdown body of the email.
        :param recipients: The list of recipient email addresses.
        :return: The result of the email sending operation.
        """
        sender = os.environ.get("SMTP_EMAIL")
        password = os.environ.get("SMTP_PASSWORD")

        if not sender or not password:
            return json.dumps(
                {
                    "status": "error",
                    "message": "SMTP_EMAIL or SMTP_PASSWORD is not configured.",
                }
            )

        try:
            html_body = self._markdown_to_html(body)

            msg = MIMEMultipart("alternative")
            msg["Subject"] = subject
            msg["From"] = f"MASDAN-DX Automated Mailer <{sender}>"
            msg["To"] = ", ".join(recipients)

            # Attach plain text first, HTML second.
            # Email clients prefer the last supported part.
            msg.attach(MIMEText(body, "plain", "utf-8"))
            msg.attach(MIMEText(html_body, "html", "utf-8"))

            with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp_server:
                smtp_server.login(sender, password)
                smtp_server.sendmail(sender, recipients, msg.as_string())

            return json.dumps(
                {
                    "status": "success",
                    "message": "Markdown email sent successfully as multipart/alternative.",
                    "to": recipients,
                    "subject": subject,
                }
            )

        except Exception as e:
            return json.dumps({"status": "error", "message": str(e)})
